language: node_js
sudo: false
notifications:
  email:
    recipients:
      - tristan.wright@kitware.com
      - sebastien.jourdain@kitware.com
    on_success: change
    on_failure: always
cache:
  directories:
    - node_modules
node_js:
  - "4.1"
script:
  - npm run build:release
  - git config --global user.name "Travis CI"
  - git config --global user.email "sebastien.jourdain@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/Kitware/arctic-viewer.git
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run doc:publish; fi
after_success:
  - npm run semantic-release
